services:
  - type: web
    name: skipthegames4ai
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        value: mongodb+srv://janga:busseja@janga0.f5z2f6j.mongodb.net/damnskippy?retryWrites=true&w=majority
        sync: false
      - key: JWT_SECRET
        generateValue: true
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    domains:
      - skipthegames4ai.onrender.com