services:
  - type: web
    name: damnskippy
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: VITE_MONGODB_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true 